// jtag_matvec_system_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module jtag_matvec_system_mm_interconnect_0 (
		input  wire        clk_0_clk_clk,                                     //                                   clk_0_clk.clk
		input  wire        jtag_master_clk_reset_reset_bridge_in_reset_reset, // jtag_master_clk_reset_reset_bridge_in_reset.reset
		input  wire        matvec_reset_reset_bridge_in_reset_reset,          //          matvec_reset_reset_bridge_in_reset.reset
		input  wire [31:0] jtag_master_master_address,                        //                          jtag_master_master.address
		output wire        jtag_master_master_waitrequest,                    //                                            .waitrequest
		input  wire [3:0]  jtag_master_master_byteenable,                     //                                            .byteenable
		input  wire        jtag_master_master_read,                           //                                            .read
		output wire [31:0] jtag_master_master_readdata,                       //                                            .readdata
		output wire        jtag_master_master_readdatavalid,                  //                                            .readdatavalid
		input  wire        jtag_master_master_write,                          //                                            .write
		input  wire [31:0] jtag_master_master_writedata,                      //                                            .writedata
		output wire [11:0] matvec_avs_address,                                //                                  matvec_avs.address
		output wire        matvec_avs_write,                                  //                                            .write
		output wire        matvec_avs_read,                                   //                                            .read
		input  wire [31:0] matvec_avs_readdata,                               //                                            .readdata
		output wire [31:0] matvec_avs_writedata,                              //                                            .writedata
		output wire [3:0]  matvec_avs_byteenable,                             //                                            .byteenable
		input  wire        matvec_avs_readdatavalid,                          //                                            .readdatavalid
		input  wire        matvec_avs_waitrequest                             //                                            .waitrequest
	);

	wire         jtag_master_master_translator_avalon_universal_master_0_waitrequest;   // matvec_avs_translator:uav_waitrequest -> jtag_master_master_translator:uav_waitrequest
	wire  [31:0] jtag_master_master_translator_avalon_universal_master_0_readdata;      // matvec_avs_translator:uav_readdata -> jtag_master_master_translator:uav_readdata
	wire         jtag_master_master_translator_avalon_universal_master_0_debugaccess;   // jtag_master_master_translator:uav_debugaccess -> matvec_avs_translator:uav_debugaccess
	wire  [31:0] jtag_master_master_translator_avalon_universal_master_0_address;       // jtag_master_master_translator:uav_address -> matvec_avs_translator:uav_address
	wire         jtag_master_master_translator_avalon_universal_master_0_read;          // jtag_master_master_translator:uav_read -> matvec_avs_translator:uav_read
	wire   [3:0] jtag_master_master_translator_avalon_universal_master_0_byteenable;    // jtag_master_master_translator:uav_byteenable -> matvec_avs_translator:uav_byteenable
	wire         jtag_master_master_translator_avalon_universal_master_0_readdatavalid; // matvec_avs_translator:uav_readdatavalid -> jtag_master_master_translator:uav_readdatavalid
	wire         jtag_master_master_translator_avalon_universal_master_0_lock;          // jtag_master_master_translator:uav_lock -> matvec_avs_translator:uav_lock
	wire         jtag_master_master_translator_avalon_universal_master_0_write;         // jtag_master_master_translator:uav_write -> matvec_avs_translator:uav_write
	wire  [31:0] jtag_master_master_translator_avalon_universal_master_0_writedata;     // jtag_master_master_translator:uav_writedata -> matvec_avs_translator:uav_writedata
	wire   [2:0] jtag_master_master_translator_avalon_universal_master_0_burstcount;    // jtag_master_master_translator:uav_burstcount -> matvec_avs_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) jtag_master_master_translator (
		.clk                    (clk_0_clk_clk),                                                         //                       clk.clk
		.reset                  (matvec_reset_reset_bridge_in_reset_reset),                              //                     reset.reset
		.uav_address            (jtag_master_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (jtag_master_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (jtag_master_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (jtag_master_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (jtag_master_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (jtag_master_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (jtag_master_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (jtag_master_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (jtag_master_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (jtag_master_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (jtag_master_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (jtag_master_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (jtag_master_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (jtag_master_master_byteenable),                                         //                          .byteenable
		.av_read                (jtag_master_master_read),                                               //                          .read
		.av_readdata            (jtag_master_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (jtag_master_master_readdatavalid),                                      //                          .readdatavalid
		.av_write               (jtag_master_master_write),                                              //                          .write
		.av_writedata           (jtag_master_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                  //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                  //               (terminated)
		.av_begintransfer       (1'b0),                                                                  //               (terminated)
		.av_chipselect          (1'b0),                                                                  //               (terminated)
		.av_lock                (1'b0),                                                                  //               (terminated)
		.av_debugaccess         (1'b0),                                                                  //               (terminated)
		.uav_clken              (),                                                                      //               (terminated)
		.av_clken               (1'b1),                                                                  //               (terminated)
		.uav_response           (2'b00),                                                                 //               (terminated)
		.av_response            (),                                                                      //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                  //               (terminated)
		.av_writeresponsevalid  ()                                                                       //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (12),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (1),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) matvec_avs_translator (
		.clk                    (clk_0_clk_clk),                                                         //                      clk.clk
		.reset                  (matvec_reset_reset_bridge_in_reset_reset),                              //                    reset.reset
		.uav_address            (jtag_master_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (jtag_master_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (jtag_master_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (jtag_master_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (jtag_master_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (jtag_master_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (jtag_master_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (jtag_master_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (jtag_master_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (jtag_master_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (jtag_master_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (matvec_avs_address),                                                    //      avalon_anti_slave_0.address
		.av_write               (matvec_avs_write),                                                      //                         .write
		.av_read                (matvec_avs_read),                                                       //                         .read
		.av_readdata            (matvec_avs_readdata),                                                   //                         .readdata
		.av_writedata           (matvec_avs_writedata),                                                  //                         .writedata
		.av_byteenable          (matvec_avs_byteenable),                                                 //                         .byteenable
		.av_readdatavalid       (matvec_avs_readdatavalid),                                              //                         .readdatavalid
		.av_waitrequest         (matvec_avs_waitrequest),                                                //                         .waitrequest
		.av_begintransfer       (),                                                                      //              (terminated)
		.av_beginbursttransfer  (),                                                                      //              (terminated)
		.av_burstcount          (),                                                                      //              (terminated)
		.av_writebyteenable     (),                                                                      //              (terminated)
		.av_lock                (),                                                                      //              (terminated)
		.av_chipselect          (),                                                                      //              (terminated)
		.av_clken               (),                                                                      //              (terminated)
		.uav_clken              (1'b0),                                                                  //              (terminated)
		.av_debugaccess         (),                                                                      //              (terminated)
		.av_outputenable        (),                                                                      //              (terminated)
		.uav_response           (),                                                                      //              (terminated)
		.av_response            (2'b00),                                                                 //              (terminated)
		.uav_writeresponsevalid (),                                                                      //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                   //              (terminated)
	);

endmodule
