# Auto-generated by run_fpga_jtag_matvec.py
set cable_name {USB-Blaster [USB-0]}
set base_addr 0
set seq 11
set activation {246 255 8 242 251 4 13 247 11 9 243 252 5 14 248 1}
set weights {1 252 7 246 13 13 246 7 252 1 2 251 8 245 14 12 243 244 8 252 253 4 248 12 13 247 5 255 253 7 245 242 252 255 6 245 243 8 253 254 7 244 244 7 254 253 8 243 248 14 9 253 253 9 14 248 2 4 246 243 7 255 251 11}
set timeout_ms 20000

proc signed32 {value} {
    set value [expr {$value & 0xffffffff}]
    if {$value >= 0x80000000} {
        return [expr {$value - 0x100000000}]
    }
    return $value
}

proc reg_addr {base offset} {
    return [expr {$base + $offset}]
}

puts "JTAG_MATVEC_CABLES [get_service_paths master]"
set masters [get_service_paths master]
if {[llength $masters] == 0} {
    puts "JTAG_MATVEC_ERROR reason=no_master_service"
    exit 2
}

set selected [lindex $masters 0]
foreach m $masters {
    if {[string first $cable_name $m] >= 0} {
        set selected $m
    }
}
open_service master $selected
puts "JTAG_MATVEC_MASTER $selected"

set t0 [clock milliseconds]
master_write_32 $selected [reg_addr $base_addr 16] $seq
master_write_32 $selected [reg_addr $base_addr 0] 0x2
master_write_32 $selected [reg_addr $base_addr 0] 0x4

set idx 0
foreach v $activation {
    master_write_32 $selected [reg_addr $base_addr [expr {256 + ($idx * 4)}]] $v
    incr idx
}

set idx 0
foreach v $weights {
    master_write_32 $selected [reg_addr $base_addr [expr {512 + ($idx * 4)}]] $v
    incr idx
}
set t_write [clock milliseconds]

master_write_32 $selected [reg_addr $base_addr 0] 0x1
set status 0
while {1} {
    set status [master_read_32 $selected [reg_addr $base_addr 4] 1]
    set status [lindex $status 0]
    if {($status & 0x2) != 0} {
        break
    }
    if {([clock milliseconds] - $t_write) > $timeout_ms} {
        puts "JTAG_MATVEC_ERROR reason=timeout status=$status"
        close_service master $selected
        exit 3
    }
    after 1
}
set t_poll [clock milliseconds]

set r0 [signed32 [lindex [master_read_32 $selected [reg_addr $base_addr 768] 1] 0]]
set r1 [signed32 [lindex [master_read_32 $selected [reg_addr $base_addr [expr {768 + 4}]] 1] 0]]
set r2 [signed32 [lindex [master_read_32 $selected [reg_addr $base_addr [expr {768 + 8}]] 1] 0]]
set r3 [signed32 [lindex [master_read_32 $selected [reg_addr $base_addr [expr {768 + 12}]] 1] 0]]
set compute_cycles [lindex [master_read_32 $selected [reg_addr $base_addr 64] 1] 0]
set core_total_cycles [lindex [master_read_32 $selected [reg_addr $base_addr 68] 1] 0]
set last_run_id [lindex [master_read_32 $selected [reg_addr $base_addr 72] 1] 0]
set debug_status [lindex [master_read_32 $selected [reg_addr $base_addr 76] 1] 0]
set t_read [clock milliseconds]

close_service master $selected
puts "JTAG_MATVEC_RESULT seq=$seq status=$status debug_status=$debug_status compute_cycles=$compute_cycles core_total_cycles=$core_total_cycles last_run_id=$last_run_id r0=$r0 r1=$r1 r2=$r2 r3=$r3 write_ms=[expr {$t_write - $t0}] poll_ms=[expr {$t_poll - $t_write}] read_ms=[expr {$t_read - $t_poll}] elapsed_ms=[expr {$t_read - $t0}]"
