// jtag_matvec_system.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module jtag_matvec_system (
		input  wire       CLOCK_50_clk, // CLOCK_50.clk
		output wire [7:0] HEX0_export,  //     HEX0.export
		output wire [7:0] HEX1_export,  //     HEX1.export
		output wire [7:0] HEX2_export,  //     HEX2.export
		output wire [7:0] HEX3_export,  //     HEX3.export
		output wire [7:0] HEX4_export,  //     HEX4.export
		output wire [7:0] HEX5_export,  //     HEX5.export
		input  wire       KEY_reset_n,  //      KEY.reset_n
		output wire [9:0] LEDR_export   //     LEDR.export
	);

	wire  [31:0] jtag_master_master_readdata;                // mm_interconnect_0:jtag_master_master_readdata -> jtag_master:master_readdata
	wire         jtag_master_master_waitrequest;             // mm_interconnect_0:jtag_master_master_waitrequest -> jtag_master:master_waitrequest
	wire  [31:0] jtag_master_master_address;                 // jtag_master:master_address -> mm_interconnect_0:jtag_master_master_address
	wire         jtag_master_master_read;                    // jtag_master:master_read -> mm_interconnect_0:jtag_master_master_read
	wire   [3:0] jtag_master_master_byteenable;              // jtag_master:master_byteenable -> mm_interconnect_0:jtag_master_master_byteenable
	wire         jtag_master_master_readdatavalid;           // mm_interconnect_0:jtag_master_master_readdatavalid -> jtag_master:master_readdatavalid
	wire         jtag_master_master_write;                   // jtag_master:master_write -> mm_interconnect_0:jtag_master_master_write
	wire  [31:0] jtag_master_master_writedata;               // jtag_master:master_writedata -> mm_interconnect_0:jtag_master_master_writedata
	wire  [31:0] mm_interconnect_0_matvec_avs_readdata;      // matvec:avs_readdata -> mm_interconnect_0:matvec_avs_readdata
	wire         mm_interconnect_0_matvec_avs_waitrequest;   // matvec:avs_waitrequest -> mm_interconnect_0:matvec_avs_waitrequest
	wire  [11:0] mm_interconnect_0_matvec_avs_address;       // mm_interconnect_0:matvec_avs_address -> matvec:avs_address
	wire         mm_interconnect_0_matvec_avs_read;          // mm_interconnect_0:matvec_avs_read -> matvec:avs_read
	wire   [3:0] mm_interconnect_0_matvec_avs_byteenable;    // mm_interconnect_0:matvec_avs_byteenable -> matvec:avs_byteenable
	wire         mm_interconnect_0_matvec_avs_readdatavalid; // matvec:avs_readdatavalid -> mm_interconnect_0:matvec_avs_readdatavalid
	wire         mm_interconnect_0_matvec_avs_write;         // mm_interconnect_0:matvec_avs_write -> matvec:avs_write
	wire  [31:0] mm_interconnect_0_matvec_avs_writedata;     // mm_interconnect_0:matvec_avs_writedata -> matvec:avs_writedata
	wire         rst_controller_reset_out_reset;             // rst_controller:reset_out -> [matvec:reset, mm_interconnect_0:jtag_master_clk_reset_reset_bridge_in_reset_reset, mm_interconnect_0:matvec_reset_reset_bridge_in_reset_reset]

	jtag_matvec_system_jtag_master #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (2)
	) jtag_master (
		.clk_clk              (CLOCK_50_clk),                     //          clk.clk
		.clk_reset_reset      (~KEY_reset_n),                     //    clk_reset.reset
		.master_address       (jtag_master_master_address),       //       master.address
		.master_readdata      (jtag_master_master_readdata),      //             .readdata
		.master_read          (jtag_master_master_read),          //             .read
		.master_write         (jtag_master_master_write),         //             .write
		.master_writedata     (jtag_master_master_writedata),     //             .writedata
		.master_waitrequest   (jtag_master_master_waitrequest),   //             .waitrequest
		.master_readdatavalid (jtag_master_master_readdatavalid), //             .readdatavalid
		.master_byteenable    (jtag_master_master_byteenable),    //             .byteenable
		.master_reset_reset   ()                                  // master_reset.reset
	);

	QkJtagDecodeMatVecRegTopPdWrapper matvec (
		.clk               (CLOCK_50_clk),                               // clock.clk
		.reset             (rst_controller_reset_out_reset),             // reset.reset
		.avs_address       (mm_interconnect_0_matvec_avs_address),       //   avs.address
		.avs_read          (mm_interconnect_0_matvec_avs_read),          //      .read
		.avs_write         (mm_interconnect_0_matvec_avs_write),         //      .write
		.avs_byteenable    (mm_interconnect_0_matvec_avs_byteenable),    //      .byteenable
		.avs_writedata     (mm_interconnect_0_matvec_avs_writedata),     //      .writedata
		.avs_readdata      (mm_interconnect_0_matvec_avs_readdata),      //      .readdata
		.avs_waitrequest   (mm_interconnect_0_matvec_avs_waitrequest),   //      .waitrequest
		.avs_readdatavalid (mm_interconnect_0_matvec_avs_readdatavalid), //      .readdatavalid
		.LEDR              (LEDR_export),                                //  leds.export
		.HEX0              (HEX0_export),                                //  hex0.export
		.HEX1              (HEX1_export),                                //  hex1.export
		.HEX2              (HEX2_export),                                //  hex2.export
		.HEX3              (HEX3_export),                                //  hex3.export
		.HEX4              (HEX4_export),                                //  hex4.export
		.HEX5              (HEX5_export)                                 //  hex5.export
	);

	jtag_matvec_system_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                     (CLOCK_50_clk),                               //                                   clk_0_clk.clk
		.jtag_master_clk_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),             // jtag_master_clk_reset_reset_bridge_in_reset.reset
		.matvec_reset_reset_bridge_in_reset_reset          (rst_controller_reset_out_reset),             //          matvec_reset_reset_bridge_in_reset.reset
		.jtag_master_master_address                        (jtag_master_master_address),                 //                          jtag_master_master.address
		.jtag_master_master_waitrequest                    (jtag_master_master_waitrequest),             //                                            .waitrequest
		.jtag_master_master_byteenable                     (jtag_master_master_byteenable),              //                                            .byteenable
		.jtag_master_master_read                           (jtag_master_master_read),                    //                                            .read
		.jtag_master_master_readdata                       (jtag_master_master_readdata),                //                                            .readdata
		.jtag_master_master_readdatavalid                  (jtag_master_master_readdatavalid),           //                                            .readdatavalid
		.jtag_master_master_write                          (jtag_master_master_write),                   //                                            .write
		.jtag_master_master_writedata                      (jtag_master_master_writedata),               //                                            .writedata
		.matvec_avs_address                                (mm_interconnect_0_matvec_avs_address),       //                                  matvec_avs.address
		.matvec_avs_write                                  (mm_interconnect_0_matvec_avs_write),         //                                            .write
		.matvec_avs_read                                   (mm_interconnect_0_matvec_avs_read),          //                                            .read
		.matvec_avs_readdata                               (mm_interconnect_0_matvec_avs_readdata),      //                                            .readdata
		.matvec_avs_writedata                              (mm_interconnect_0_matvec_avs_writedata),     //                                            .writedata
		.matvec_avs_byteenable                             (mm_interconnect_0_matvec_avs_byteenable),    //                                            .byteenable
		.matvec_avs_readdatavalid                          (mm_interconnect_0_matvec_avs_readdatavalid), //                                            .readdatavalid
		.matvec_avs_waitrequest                            (mm_interconnect_0_matvec_avs_waitrequest)    //                                            .waitrequest
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~KEY_reset_n),                   // reset_in0.reset
		.clk            (CLOCK_50_clk),                   //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
